brew install awscli
brew install bash
brew install berkeley-db
brew install binutils
brew install brotli
brew install c-ares
brew install coreutils
brew install csvkit
brew install diffutils
brew install ed
brew install fdupes
brew install gawk
brew install gdbm
brew install gettext
brew install git
brew install gmp
brew install gnu-indent
brew install gnu-sed
brew install gnu-tar
brew install gnu-which
brew install grep
brew install icu4c
brew install jemalloc
brew install jq
brew install ldns
brew install less
brew install libcbor
brew install libev
brew install libevent
brew install libfido2
brew install libidn2
brew install libunistring
brew install libuv
brew install libyaml
brew install lua
brew install lz4
brew install m4
brew install make
brew install mas
brew install mpdecimal
brew install mpfr
brew install mysql
brew install ncurses
brew install netcat
brew install nghttp2
brew install nmap
brew install node
brew install oniguruma
brew install openssh
brew install openssl
brew install packer
brew install pbc
brew install pcre
brew install pcre2
brew install perl
brew install pkg-config
brew install protobuf
brew install python
brew install rbenv
brew install readline
brew install ruby
brew install ruby-build
brew install six
brew install socat
brew install sqlite
brew install telnet
brew install tree
brew install unzip
brew install vim
brew install wdiff
brew install wget
brew install xz
brew install youtube-dl
brew install zstd
brew install 1password
brew install 1password-cli
brew install adoptopenjdk11
brew install alfred
brew install android-file-transfer
brew install appcleaner
brew install beyond-compare
brew install boom-3d
brew install dropbox
brew install evernote
brew install firefox
brew install gas-mask
brew install google-chrome
brew install guitar-pro
brew install hyperdock
brew install istat-menus
brew install iterm2
brew install keka
brew install keyboard-maestro
brew install kindle
brew install openemu
brew install pdfsam-basic
brew install proxifier
brew install royal-tsx
brew install slack
brew install sublime-text
brew install switchresx
brew install vagrant
brew install virtualbox
brew install vscodium
brew install webex-meetings
brew install weka
brew install zoom

